version: '3.8'

services:
  db:
    image: postgres:13
    container_name: overseer_db
    environment:
      POSTGRES_USER: overseer
      POSTGRES_PASSWORD: overseer_pass
      POSTGRES_DB: overseer_db
    ports:
      - "5432:5432"
    volumes:
      - overseer_data:/var/lib/postgresql/data
    restart: always

volumes:
  overseer_data:
    driver: local
