version: '3.8'

services:
  db:
    image: postgres:13
    container_name: overseer_db
    environment:
      POSTGRES_USER: overseer
      POSTGRES_PASSWORD: overseer_pass
      POSTGRES_DB: overseer_db
    volumes:
      - overseer_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend
    expose:
      - "5432"  # закрыт от хоста

  crud_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: overseer_crud
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - backend

  report_service:
    build:
      context: ./reports
      dockerfile: Dockerfile
    container_name: overseer_report
    depends_on:
      - db
    ports:
      - "8001:8001"
    networks:
      - backend

volumes:
  overseer_data:

networks:
  backend:
    driver: bridge
