version: '3.8'

services:
  db:
    image: postgres:13
    container_name: overseer_db
    environment:
      POSTGRES_USER: overseer
      POSTGRES_PASSWORD: overseer_pass
      POSTGRES_DB: overseer_db
    volumes:
      - overseer_data:/var/lib/postgresql/data
    restart: always
    expose:
      - "5432"
    networks:
      - backend

  crud_service:
    build:
      context: ./app
    container_name: overseer_crud
    depends_on:
      - db
      - report_service
      - minio
    ports:
      - "8000:8000"
    networks:
      - backend
    restart:
      always

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - backend  

  report_service:
    build: ./reports
    depends_on:
      - minio
    environment:
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    container_name: report_service
    ports:
      - "8001:8001"
    networks:
      - backend  

volumes:
  overseer_data:
  minio_data:

networks:
  backend:
    driver: bridge

